head-inventory:
  enabled: true           # Enables interactive player selection inventory.

  online-mode: true       # Should the plugin retrieve player heads from the Mojang API
                          # or assign random monster heads.
                          # If set to false, cache is also disabled.
  cache:
    queue-tick: 20        # When the first head in queue gets its data from the Mojang API.
                          # Default value is every 20 ticks (approx. 1 sec).
                          # (Mojang API limit is 600 requests per 10 min).

    expire-tick: 900000   # When a head should be re-cached.
                          # Default value is every 900 000 millis (approx. 15 min).

    refresh-tick: 6000    # When re-caching happens.
                          # Re-caching puts every expired head back into the queue.
                          # Default value is every 6 000 ticks (approx. 5 min).

bungeecord:
  enabled: true           # Enables cross-server support using BungeeCord as a proxy.

  playerlist-tick: 100    # When the plugin asks BungeeCord for a player-list.
                          # Default value is every 100 ticks (approx. 5 sec).