name: UtilTPA
author: novosadkry
main: cz.novosadkry.UtilTPA.Main
version: 2.0
api-version: 1.16

commands:
  tpa:
    usage: /tpa nick
  tpaccept:
    usage: /tpaccept, /tpaccept nick
    aliases: [tpy, tpyes]
  tpdeny:
    usage: /tpdeny, /tpdeny nick
    aliases: [tpn, tpno]
  back:
    usage: /back